- hosts: dev
  tasks:
    - name: download tomcat from site
      get_url :
        url : https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz
        dest : /root

    - name : untar the tomcat
      command : tar -zxvf apache-tomcat-9.0.87.tar.gz

    - name : manager-gui line
      command : sed -i '55  a\<role rolename="manager-gui"/>' apache-tomcat-9.0.87/conf/tomcat-users.xml

    - name : manager-script line
      command : sed -i '56  a\<role rolename="manager-script"/>' apache-tomcat-9.0.87/conf/tomcat-users.xml

    - name : username password
      command : sed -i '55  a\<user username="tomcat" password="ramesh123" roles="manager-gui, manager-script"/>' apache-tomcat-9.0.87/conf/tomcat-users.xml

    - name : delete line21
      command : sed -i '21d' apache-tomcat-9.0.87/webapps/manager/META-INF/context.xml

    - name : delete line22
      command : sed -i '22d' apache-tomcat-9.0.87/webapps/manager/META-INF/context.xml

    - name: Run Tomcat
      shell: nohup apache-tomcat-9.0.87/bin/startup.sh
